### PR TITLE
Librarify

### PR DESCRIPTION
**Pull request by jcb91**
Simplify library code by returning a new plugin as a closure for the per-plugin config & keyboard shortcuts. Incorporate history from @EWouters 2to3 fork.

### CODE REVIEW

**Comment by jfbercher** [comment]
Merged.

**Comment by jfbercher** [comment]
Unfortunately, hotkeys don't work as intended. 
Actually, the keyboard shortcuts are mapped to the last loaded extension. Sometimes "Ctrl-L" corresponds to code_prettify, sometimes to 2to3. 
I have looked after that quite a long time but I don't find what happens. It seems that the handler retains the context of the last loaded extension. I tried to bind the handler to the actual context but this do not changes things.  I have tried to rewrite the library in an object oriented way https://github.com/jfbercher/code_prettify/commit/9e42da818ef32655ea81d0be7217df53e0fbfa72; this works but doesn't solve the hotkeys issue. 
For now I have re-added the hotkeys definition in the extensions' scripts https://github.com/jfbercher/code_prettify/commit/7138003e1b27aea32a96c0d3c7f23c649d27e90a. But in this situation again, strange things appear, and it is needed to to use different handlers command so  that the hotkeys are correctly affected (I use a stub variable in the calls). 
Any idea/explanation/clue will be appreciated...

**Comment by jcb91** [comment]
> Actually, the keyboard shortcuts are mapped to the last loaded extension.

Oh dear :( my mistake, sorry, it'll be this stupid javascript context-confusion again, I guess, though I thought we'd be ok by executing the function. Oh well, I guess I don't understand it properly yet, it's always made my head swim 😜

> But in this situation again, strange things appear, and it is needed to to use different handlers command so that the hotkeys are correctly affected (I use a stub variable in the calls).

Not sure what you mean here; what strange things appear?

**Comment by jcb91** [comment]
After further inspection, I've found that the problem is nothing to do with javascript contexts, and actually relates to how Jupyter stores keyboard shortcuts. It basically wants action names, rather than the objects we were passing. If you pass an object with a `handler` key, it uses the `handler` function to define a new action, whose name is derived from a string representation of the function. The upshot of this is that if your two functions have the same string representation, then the second one's new action overwrites the first one's, despite the fact that the two functions are actually different because of the context in which they execute. This is true no matter where the functions were defined, so if you use the same variable names (`cfg`, `mod_name`, etc) in separate files, you'll still get this problem. See my librarify branch for an updated solution making use of actions with explicit names.

This might be considered a Jupyter bug, although it's a pretty rare edge-case, I imagine. It could though, be neatly solved by adding a counter for the number of auto-generated functions, so that they can be given unique names.

**Comment by jfbercher** [comment]
Yes, good spot! I identified that it was something linked to the string representation of the handler function, thus my attempt to use a stub parameter (which leads to a different string representation). I also tried actions, but with no success. The key is to specify the prefix in the `actions.register(action, name, prefix)` which I did not. We see clearly the importance of that prefix now!
Thanks for all. I will test that later and try to update/merge in the repo.

**Comment by jfbercher** [comment]
@jcb91, @EWouters  
-  updated the library with @jcb91 's suggestions and bugfixes
-  updated plugins to use the modified lib
- reorganized the READMEs to provide one README per plugin + a general README for the library
- updated the lib description, with description of parameters, example of usage and history
- added autopep8 plugin, following @kenkoooo, to provide an example of  lib use for building a new plugin

I wonder if we should not rename the repo with the name of the lib (a better name would be welcome!). 

@jcb91 It seems that it works pretty well now and that it could be pushed to jupyter_contrib_nbextensions (with history as you know so well do it / I 'll be glad to have a small explanation), perhaps after revising my updates to the various README.

**Comment by jcb91** [comment]
> * reorganized the READMEs to provide one README per plugin + a general README for the library

good idea 👍 

> it could be pushed to jupyter_contrib_nbextensions (with history as you know so well do it / I 'll be glad to have a small explanation), perhaps after revising my updates to the various README

Ok, I'll have a quick look through the readmes, then knock together somehting to show what I do to merge in another repo...

**Comment by jcb91** [comment]
> I wonder if we should not rename the repo with the name of the lib (a better name would be welcome!).

Could be a good idea. Maybe add 'nbextensions' as well to make it clear they're included? Not sure if that's a good idea or not.

I see what you mean, a better name would be helpful, but I'm having difficulty coming up with one that's more expressive. The best I can come up with is probably `CodeCellThroughKernelTransformer`, or `TransformCodeCellThroughKernel`, but I'm not sure either is much good, really...

I've submitted PR #6 for the readmes.

I must also admit I'm not a big fan of the OOP approach in this instance, as it seems to just add a whole lot of complexity attempting to adjust for different `this` contexts without any obvious benefit, but to each their own, I guess 😉

**Comment by jfbercher** [comment]
> I've  submitted PR #6 for the readmes.

Thanks again!

> I must also admit I'm not a big fan of the OOP approach in this instance, as it seems to just add a whole lot of complexity attempting to adjust for different this contexts without any obvious benefit, but to each their own, I guess 

Not so much complexity, I think. I changed it that way when I attempted to solve the keyboard shorcut issue 
- tried to proxify the handler using `$.proxy(function, this)`; could also be used in the standard functional context, ok :)
- also needed to access the different functions of the lib, and this is simple if the plugin is an object instance. 

But clearly, at the end, there is no obvious benefit here.

**Comment by jcb91** [comment]
Sure, it's a matter of personal preference here 😄

**Pull request merged**
