### PR TITLE
make everything configurable

### PR DESCRIPTION
**Pull request by jcb91**
* switch to a print-json model for getting formatted text from kernel
* make kernel-specific code configurable
* make hotkey & verbosity configurable
* update readme

### CODE REVIEW

**Comment by jfbercher** [comment]
@jcb91 

WOW!!!

This is a great work and major improvements! Thanks a lot! 

I tried myself to implement something for converting several cells but failed because of the asynchronous replies from the kernels. You succeeded using promises. I have begin to study that and will learn from your code.  
You also solved properly the problem of text encoding using the json exchange format; I used it for sending the text to kernels but didn't realize how to recover it in return, thus ending with ad-hoc replacements. The good idea was indeed to use kernel specific modules to encode the results and print them (another good idea!). 

I think that it would be nice to add a keyboard shortcut to reformat the whole notebook. This should be easy since everything is nearly ready. Also I think that we shall find away to enable the `2to3_cell` nbexension as a kind of plugin of this one. At least it should be possible to directly use the `code_prettify` code using an adhoc yaml file, no?

**Comment by jfbercher** [comment]
@jcb91 
- Don't you want to submit these updates yourself to `jupyter_contrib_nbextensions`?
- I have a pending project, nearly ready now I think, at https://github.com/jfbercher/jupyter_nbTranslate If you can have a look at it, I will certainly welcome comments, suggestions, improvements...

**Comment by jfbercher** [comment]
Added  commit https://github.com/jfbercher/code_prettify/commit/8512d09710b2f63f035d70e824cf06c67162feaa  introducing a keyboard shortcut to prettify the whole notebook

**Comment by jfbercher** [comment]
>At least it should be possible to directly use the code_prettify code using an adhoc yaml file, no?

Ah Ah. Not so simple. Tried but `nbextensions_configurator`  seems to not allow to require the same js several times.

**Comment by jcb91** [comment]
> because of the asynchronous replies from the kernels. You succeeded using promises

The promises aren't actually _necessary_, as such, it'sthe creation of a new closure (function) to ensure the cell referred to by the text-setting function is the one intended which got it to work for me. I've just only recently started using promises, and liked the flow that they provide for asynchronous operations like this. (indeed, I wrote the promise parts first, then had to fix the multi-cell workings with an IIFE in cf3c411dda400208e63081fe848d5f2a3c0eae01).

> I think that it would be nice to add a keyboard shortcut to reformat the whole notebook.

Sure, sounds a good plan 😄 

> Don't you want to submit these updates yourself to jupyter_contrib_nbextensions?

Well, I thought it best to put them in upstream first, so to speak :) I can put a PR in there too, once it'sworking well here. I found with the scratchpad nbextension that I could add the upstream repo as a remote of the contrib repo, then rename/move everything to be in the correct directory for contrib, and it would merge successfully. The key part is then that the commits are the same (have same hash), and because git is quite good at tracking renames, I can merge further changes in from upstream without further effort.

> find away to enable the 2to3_cell nbexension as a kind of plugin of this one

Yes, this should make things fairly re-useable, but it will require a little modification, I guess, mainly probably exporting more functions in form the define

> Ah Ah. Not so simple. Tried but nbextensions_configurator seems to not allow to require the same js several times.

True, it won't allow the same main require path for two different nbextensions. But, I think a better approach would be to add a stub js file for 2to3 which can require the main functionality from code_prettify (or possibly to make both require from a library-type file of functions).

**Comment by jfbercher** [comment]
- made a library of useful and shared functions. The library can be used by any extension which has to execute some code, via the current kernel, on text from selected (or all) cells e845d93  
- updated code_prettify to use the shared library 09e69ce  
- added the python 2 to 3 converter, updated to use the shared library 1b82fc9

**Comment by jfbercher** [comment]
@jcb91 
I have made a module, with an AMD loader, of the functions that can be shared between extension using the paradigm "exec something using the current kernel on selected cells", currently `code_prettify` and `2to3`. A difficulty that I encountered is that since both extensions access the same (separated) namespace, their variables with same names overwrites each other. A consequence is that I didn't found a way to assign the keyboard shortcuts by a call to a function in the shared library. If you see if it is possible? Anyway that is not very important... Happy new year!

**Comment by jcb91** [comment]
>I have made a module, with an AMD loader

oh neat!

> currently `code_prettify` and `2to3`

I was going to say we could something include along the lines of the fork [kenkoooo/jupyter-autopep8](https://github.com/kenkoooo/jupyter-autopep8), but it's pretty much just changing the default python-kernel code, so maybe just add to README?

> A difficulty that I encountered is that since both extensions access the same (separated) namespace, their variables with same names overwrites each other

I'm not sure I follow what you mean here? I guess that `mod_edit_shortcuts` and the like need to be per-plugin? I've made a stab at a simpler library by just wrapping the whole thing in a closure to make the `cfg` and `mod_name` variables per-plugin - see https://github.com/jfbercher/code_prettify/pull/5

**Comment by jfbercher** [comment]
Nice PR #5! Damn, I was looking for too complicated things. The simple wrapping of all functions into `define_plugin` was a simple solution to isolate variables per plugin, indeed. Well done.
Yes, we can refer to the `autopep8` fork in the README with the recipe to change the formater and take advantage of the more robust and improved implementation (I was not aware of this fork).

**Pull request merged**
